#!/usr/bin/env python

import sys

from rqt_dodo.scanner_module import HomePlugin
from rqt_gui.main import Main

plugin = 'rqt_dodo'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
